Конструкция try catch - **это специальная инструкция из двух блоков, которая позволяет перехватить все исключения и их обработать**. Любые исключения, которые будут выброшены кодом, расположенным внутри этого блока, будут перехвачены и переданы во второй блок. Если ошибки не было, то этот блок пропускается. 

ИСПОЛЬЗУЕТСЯ В КОНСТРУКЦИИ `async await`  ЧТОБЫ ВЫЛОВИТЬ ОШИБОК


"try catch" - это механизм обработки ошибок в JavaScript, который позволяет программистам ловить и обрабатывать исключения в своих программах.

"try catch" блок состоит из двух частей: блока "try" и блока "catch". Код, который может вызвать ошибку, помещается в блок "try", а код для обработки ошибки помещается в блок "catch".

Если код в блоке "try" вызывает исключение, выполнение программы прекращается и управление переходит к блоку "catch". В блоке "catch" можно написать код для обработки ошибки, например, вывести сообщение об ошибке на экран или записать информацию об ошибке в журнал.

Пример использования "try catch" в JavaScript:

`try {   // код, который может вызвать ошибку   
	`let x = y / 0; }
`` catch (error) {   // код для обработки ошибки   
`console.log('Произошла ошибка: ' + error.message); }`

В этом примере, если значение переменной "y" равно 0, код в блоке "try" вызовет ошибку деления на 0. Управление выполнения программы перейдет к блоку "catch", который выведет сообщение об ошибке на экран.

[[Ассинхронность]]
